source 'https://supermarket.chef.io'

cookbook 'build-essential', '~> 2.2.3'
cookbook 'apt', '~> 2.7.0'
cookbook 'nginx', '~> 2.7.6'
cookbook 'nodejs', '~> 2.4'
cookbook 'mysql', '~> 5.0'
cookbook 'php', '~> 1.5.0'
cookbook 'php5-fpm', '= 0.2.2'
cookbook 'composer', '~> 2.1.0'
cookbook 'git', '~> 4.2.2'
cookbook 'java', '~> 1.31.0'
cookbook 'elasticsearch', '~> 0.3.13'
cookbook 'base', path: './cookbooks/base/'