version: "2"
services:
  nginx:
    image: ongr/nginx
    links:
      - fpm
    ports:
      - "$LOCAL_NGINX_PORT:80"
    volumes:
      - .docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - app-sync:/var/www:nocopy
    networks:
      - frontend
  fpm:
    build:
      context: .docker/build/fpm
      args:
        LOCAL_USER_ID: $LOCAL_USER_ID
        LOCAL_GROUP_ID: $LOCAL_GROUP_ID
    user: "$LOCAL_USER_ID:$LOCAL_GROUP_ID"
    links:
      - mariadb
    volumes:
      - .docker/.composer:/.composer
      - app-sync:/var/www:nocopy
      - "$LOCAL_SSH_PRIVATE_KEY:/home/user/.ssh/id_rsa:ro"
    networks:
      - frontend
      - backend
    environment:
      XDEBUG_CONFIG: remote_host=172.27.0.1
  npm:
    image: ongr/nodejs:6.4.0
    user: "$LOCAL_USER_ID:$LOCAL_GROUP_ID"
    volumes:
      - .docker/.npm:/home/.npm
      - app-sync:/home/app:nocopy
      - /usr/local/lib/node_modules
    networks:
      - frontend
  mariadb-data:
    image: tianon/true
    volumes:
      - /var/lib/mysql
    networks:
      - backend
  mariadb:
    image: mariadb:10.2.6
    ports:
      - "$LOCAL_MYSQL_PORT:13306"
    volumes_from:
      - "mariadb-data"
    environment:
#      MYSQL_DATABASE: "$MYSQL_DATABASE"
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend
volumes:
  app-sync:
    external: true
networks:
  frontend:
    driver: bridge
    ipam:
      config:
      - subnet: 172.27.0.0/24
  backend:
    driver: bridge
    ipam:
      config:
      - subnet: 172.27.1.0/24
