---
- hosts: remote
  become: true
  vars_files:
    - ansible/defaults/main.yml
  roles:
    - base
    - nginx
    - mariadb
    - elasticsearch
    - php
    - composer
    - nodejs
    - remote
    - fail2ban
