---
- name: Set the hostname in /etc/hostname
  lineinfile: dest=/etc/hostname line="{{ remote.hostname }}" regexp=".*"
  register: added_hostname

- name: Set the hostname
  shell: hostname {{ remote.hostname }}
  when: added_hostname.changed

- name: Update /etc/hosts
  template: src=hosts.tpl dest=/etc/hosts

- name: Add default index
  copy: src=index.html dest=/usr/share/nginx/html/

- name: Add OPcache reset
  copy: src=iFEzvlepqNf.php dest=/usr/share/nginx/html/

- name: Add web group
  group: name=web state=present

- name: Add dev user
  user: name={{ remote.user }} comment="Development user" group={{ remote.group }}

- name: Add dev user umask
  lineinfile: dest="/home/{{ remote.user }}/.bashrc" line="umask 0002"

- name: Create shared directory
  file:
    path: "{{ base.projectdir }}/shared/{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - app/config
    - var/logs

- name: Add parameters.yml
  copy: src=parameters.yml dest="{{ base.projectdir }}/shared/app/config/parameters.yml"

- name: Set ownership and permissions
  file:
    path: "{{ base.projectdir }}"
    recurse: yes
    owner: "{{ remote.user }}"
    group: "{{ remote.group }}"
    mode: g+swx
