language: php
php:
  - 5.4
  - 5.5
  - 5.6
services:
  - elasticsearch
install:
  - composer install --no-interaction
  - npm install
  - npm link
before_script:
  - app/console ongr:es:index:create
  - app/console ongr:es:type:update --force
  - app/console ongr:es:index:import --raw src/ONGR/DemoBundle/Resources/data/contents.json
  - app/console ongr:es:index:import --raw src/ONGR/DemoBundle/Resources/data/categories.json
  - app/console ongr:es:index:import --raw src/ONGR/DemoBundle/Resources/data/products.json
  - cp src/ONGR/DemoBundle/Tests/Acceptance/parameters.js.dist src/ONGR/DemoBundle/Tests/Acceptance/parameters.js
  - php -S localhost:8000 web/app_dev.php &
  - sleep 3
script:
  - bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - bin/phpcs -p --standard=$TRAVIS_BUILD_DIR/vendor/ongr/ongr-strict-standard/Ongr --extensions=php ./src
  - casperjs test src/ONGR/DemoBundle/Tests/Acceptance/test.js
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
