# place here some default project parameters. It should be rewritten in parameters.yml if needed
parameters:
    base_url: 'http://%project_host%'
    font_url: '//%project_host%'
    cdn_base_url: '//%project_host%'
    cdn_url: '/'
    cdn_url_ssl: '%cdn_base_url%'
    cdn_path: '%kernel.root_dir%/../web'
    assetic.filter.compass.images_dir: '%kernel.root_dir%/Resources/styles/inc/images'
    assetic.filter.compass.generated_images_path: '%kernel.root_dir%/../web/images'
    assetic.filter.compass.http_path: '%cdn_base_url%'
    assetic.filter.compass.fonts_dir: fonts
    assetic.filter.compass.fonts_path: '%kernel.root_dir%/../web'
    assetic.filter.compass.http_fonts_path: '%font_url%/fonts'
    assetic.filter.compass.http_fonts_dir: fonts
    asset_reset: 1
    top_cms_links:
      - about
