ongr_demo:
    resource: "@ONGRDemoBundle/Resources/config/routing.yml"
    prefix:   /

ongr_content_snippet:
    resource: "@ONGRContentBundle/Resources/config/routing.yml"

ongr_translation_ui:
    resource: "@ONGRTranslationsBundle/Resources/config/routing.yml"
    prefix:   /translations

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"