#Content controller
onager_demo_homepage:
    path:     /
    defaults: { _controller: ONGRDemoBundle:Content:homePage }

#Search controller
ongr_search_page:
    pattern: /search
    methods:  [GET]
    defaults:
        _controller: ONGRFilterManagerBundle:Manager:manager
        managerName: "product_list"
        template: "ONGRDemoBundle:Product:search.html.twig"

### Proxy routes

#Category
_ongr_category_tree:
    pattern:  /_proxy/tree/{theme}/{maxLevel}/{partialTree}/{selectedCategory}
    defaults:
        _controller: ONGRDemoBundle:Category:categoryTree
        theme: "top"
        maxLevel: 2
        partialTree: "pt"
        selectedCategory: null

_ongr_breadcrumbs:
    pattern:  /_proxy/breadcrumbs/{theme}/{maxLevel}/{partialTree}/{selectedCategory}
    methods:  [GET]
    defaults:
        _controller: ONGRDemoBundle:Category:categoryTree
        theme: "breadcrumbs"
        maxLevel: 20
        partialTree: "pt"
        selectedCategory: null