parameters:
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     ongr
    database_user:     root
    database_password: root

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt

    elasticsearch_index_name: ongr
    elasticsearch_number_of_replicas: 0
    elasticsearch_number_of_shards: 1

    shop_url_origin: http://shop.ongr.local
