---
- set_fact: php_path="/etc/php/7.0"
  when: php.version == 7.0

- set_fact: php_path="/etc/php5"
  when: php.version != 7.0

- name: Install xdebug
  apt: pkg="php-xdebug" state=present
  when: php.version == 7.0

- name: Install xdebug
  apt: pkg="php5-xdebug" state=present
  when: php.version != 7.0

- name: Edit xdebug.ini
  lineinfile: dest={{ php_path }}/mods-available/xdebug.ini
              regexp='extension=xdebug.so'
              line='zend_extension=xdebug.so'
  changed_when: false

- name: Configure custom_xdebug
  template: src=custom_xdebug.tpl dest={{ php_path }}/mods-available/custom_xdebug.ini
  notify: restart fpm
  register: xdebug_conf

- name: Symlink custom_xdebug.ini
  file: src="{{ php_path }}/mods-available/custom_xdebug.ini" dest="{{ php_path }}/{{ item }}/conf.d/30-custom_xdebug.ini" state=link
  notify: restart fpm
  when: xdebug_conf.changed
  with_items:
    - fpm
    - cli

- name: Check xdebug binary
  shell: ls /usr/local/bin/debug
  ignore_errors: yes
  register: xdebug_bin
  changed_when: False

- name: Xdebug binary
  lineinfile: dest=/usr/local/bin/debug line='#!/bin/sh\nenv PHP_IDE_CONFIG=\"serverName=ongr\" XDEBUG_CONFIG=\"idekey=PHPSTORM\" SYMFONY_DEBUG=\"1\" $@' state=present create=yes owner=root mode=0755
  when: xdebug_bin|failed
